/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using CheshireCatApi.Client;
using CheshireCatApi.Api;
// uncomment below to import models
//using CheshireCatApi.Model;

namespace CheshireCatApi.Test.Api
{
    /// <summary>
    ///  Class for testing EmbedderApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmbedderApiTests : IDisposable
    {
        private EmbedderApi instance;

        public EmbedderApiTests()
        {
            instance = new EmbedderApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmbedderApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmbedderApi
            //Assert.IsType<EmbedderApi>(instance);
        }

        /// <summary>
        /// Test GetEmbedderSettings
        /// </summary>
        [Fact]
        public void GetEmbedderSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string languageEmbedderName = null;
            //var response = instance.GetEmbedderSettings(languageEmbedderName);
            //Assert.IsType<Setting>(response);
        }

        /// <summary>
        /// Test GetEmbeddersSettings
        /// </summary>
        [Fact]
        public void GetEmbeddersSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetEmbeddersSettings();
            //Assert.IsType<SettingsResponse>(response);
        }

        /// <summary>
        /// Test UpsertEmbedderSetting
        /// </summary>
        [Fact]
        public void UpsertEmbedderSettingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string languageEmbedderName = null;
            //Object body = null;
            //var response = instance.UpsertEmbedderSetting(languageEmbedderName, body);
            //Assert.IsType<Setting>(response);
        }
    }
}
