/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using CheshireCatApi.Client;
using CheshireCatApi.Api;
// uncomment below to import models
//using CheshireCatApi.Model;

namespace CheshireCatApi.Test.Api
{
    /// <summary>
    ///  Class for testing LargeLanguageModelApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LargeLanguageModelApiTests : IDisposable
    {
        private LargeLanguageModelApi instance;

        public LargeLanguageModelApiTests()
        {
            instance = new LargeLanguageModelApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LargeLanguageModelApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LargeLanguageModelApi
            //Assert.IsType<LargeLanguageModelApi>(instance);
        }

        /// <summary>
        /// Test GetLlmSettings
        /// </summary>
        [Fact]
        public void GetLlmSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string languageModelName = null;
            //var response = instance.GetLlmSettings(languageModelName);
            //Assert.IsType<Setting>(response);
        }

        /// <summary>
        /// Test GetLlmsSettings
        /// </summary>
        [Fact]
        public void GetLlmsSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetLlmsSettings();
            //Assert.IsType<SettingsResponse>(response);
        }

        /// <summary>
        /// Test UpsertLlmSetting
        /// </summary>
        [Fact]
        public void UpsertLlmSettingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string languageModelName = null;
            //Object body = null;
            //var response = instance.UpsertLlmSetting(languageModelName, body);
            //Assert.IsType<Setting>(response);
        }
    }
}
