/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using CheshireCatApi.Client;
using CheshireCatApi.Api;
// uncomment below to import models
//using CheshireCatApi.Model;

namespace CheshireCatApi.Test.Api
{
    /// <summary>
    ///  Class for testing RabbitHoleApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RabbitHoleApiTests : IDisposable
    {
        private RabbitHoleApi instance;

        public RabbitHoleApiTests()
        {
            instance = new RabbitHoleApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RabbitHoleApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RabbitHoleApi
            //Assert.IsType<RabbitHoleApi>(instance);
        }

        /// <summary>
        /// Test GetAllowedMimetypes
        /// </summary>
        [Fact]
        public void GetAllowedMimetypesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllowedMimetypes();
            //Assert.IsType<ResponseGetAllowedMimetypes>(response);
        }

        /// <summary>
        /// Test UploadFile
        /// </summary>
        [Fact]
        public void UploadFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream file = null;
            //var response = instance.UploadFile(file);
            //Assert.IsType<FileResponse>(response);
        }

        /// <summary>
        /// Test UploadMemory
        /// </summary>
        [Fact]
        public void UploadMemoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream file = null;
            //var response = instance.UploadMemory(file);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test UploadUrl
        /// </summary>
        [Fact]
        public void UploadUrlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BodyUploadUrl bodyUploadUrl = null;
            //var response = instance.UploadUrl(bodyUploadUrl);
            //Assert.IsType<WebResponse>(response);
        }
    }
}
