/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing CollectionData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollectionDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CollectionData
        //private CollectionData instance;

        public CollectionDataTests()
        {
            // TODO uncomment below to create an instance of CollectionData
            //instance = new CollectionData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CollectionData
        /// </summary>
        [Fact]
        public void CollectionDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CollectionData
            //Assert.IsType<CollectionData>(instance);
        }

        /// <summary>
        /// Test the property 'PageContent'
        /// </summary>
        [Fact]
        public void PageContentTest()
        {
            // TODO unit test for the property 'PageContent'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

        /// <summary>
        /// Test the property 'Vector'
        /// </summary>
        [Fact]
        public void VectorTest()
        {
            // TODO unit test for the property 'Vector'
        }
    }
}
