/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing CollectionsList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollectionsListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CollectionsList
        //private CollectionsList instance;

        public CollectionsListTests()
        {
            // TODO uncomment below to create an instance of CollectionsList
            //instance = new CollectionsList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CollectionsList
        /// </summary>
        [Fact]
        public void CollectionsListInstanceTest()
        {
            // TODO uncomment below to test "IsType" CollectionsList
            //Assert.IsType<CollectionsList>(instance);
        }

        /// <summary>
        /// Test the property 'Collections'
        /// </summary>
        [Fact]
        public void CollectionsTest()
        {
            // TODO unit test for the property 'Collections'
        }
    }
}
