/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing ConversationHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConversationHistoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConversationHistory
        //private ConversationHistory instance;

        public ConversationHistoryTests()
        {
            // TODO uncomment below to create an instance of ConversationHistory
            //instance = new ConversationHistory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConversationHistory
        /// </summary>
        [Fact]
        public void ConversationHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConversationHistory
            //Assert.IsType<ConversationHistory>(instance);
        }

        /// <summary>
        /// Test the property 'History'
        /// </summary>
        [Fact]
        public void HistoryTest()
        {
            // TODO unit test for the property 'History'
        }
    }
}
