/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing ConversationMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConversationMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConversationMessage
        //private ConversationMessage instance;

        public ConversationMessageTests()
        {
            // TODO uncomment below to create an instance of ConversationMessage
            //instance = new ConversationMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConversationMessage
        /// </summary>
        [Fact]
        public void ConversationMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConversationMessage
            //Assert.IsType<ConversationMessage>(instance);
        }

        /// <summary>
        /// Test the property 'Who'
        /// </summary>
        [Fact]
        public void WhoTest()
        {
            // TODO unit test for the property 'Who'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Why'
        /// </summary>
        [Fact]
        public void WhyTest()
        {
            // TODO unit test for the property 'Why'
        }
    }
}
