/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing FileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileResponse
        //private FileResponse instance;

        public FileResponseTests()
        {
            // TODO uncomment below to create an instance of FileResponse
            //instance = new FileResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileResponse
        /// </summary>
        [Fact]
        public void FileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileResponse
            //Assert.IsType<FileResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Fact]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }

        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Fact]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }
    }
}
