/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetPluginSettings200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPluginSettings200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPluginSettings200Response
        //private GetPluginSettings200Response instance;

        public GetPluginSettings200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetPluginSettings200Response
            //instance = new GetPluginSettings200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPluginSettings200Response
        /// </summary>
        [Fact]
        public void GetPluginSettings200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPluginSettings200Response
            //Assert.IsType<GetPluginSettings200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }
    }
}
