/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing MemoryRecall
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MemoryRecallTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MemoryRecall
        //private MemoryRecall instance;

        public MemoryRecallTests()
        {
            // TODO uncomment below to create an instance of MemoryRecall
            //instance = new MemoryRecall();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MemoryRecall
        /// </summary>
        [Fact]
        public void MemoryRecallInstanceTest()
        {
            // TODO uncomment below to test "IsType" MemoryRecall
            //Assert.IsType<MemoryRecall>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'Vectors'
        /// </summary>
        [Fact]
        public void VectorsTest()
        {
            // TODO unit test for the property 'Vectors'
        }
    }
}
