/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing MetaData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetaDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MetaData
        //private MetaData instance;

        public MetaDataTests()
        {
            // TODO uncomment below to create an instance of MetaData
            //instance = new MetaData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetaData
        /// </summary>
        [Fact]
        public void MetaDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" MetaData
            //Assert.IsType<MetaData>(instance);
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'When'
        /// </summary>
        [Fact]
        public void WhenTest()
        {
            // TODO unit test for the property 'When'
        }

        /// <summary>
        /// Test the property 'Docstring'
        /// </summary>
        [Fact]
        public void DocstringTest()
        {
            // TODO unit test for the property 'Docstring'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
