/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing PluginsList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PluginsListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PluginsList
        //private PluginsList instance;

        public PluginsListTests()
        {
            // TODO uncomment below to create an instance of PluginsList
            //instance = new PluginsList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PluginsList
        /// </summary>
        [Fact]
        public void PluginsListInstanceTest()
        {
            // TODO uncomment below to test "IsType" PluginsList
            //Assert.IsType<PluginsList>(instance);
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'Installed'
        /// </summary>
        [Fact]
        public void InstalledTest()
        {
            // TODO unit test for the property 'Installed'
        }

        /// <summary>
        /// Test the property 'Registry'
        /// </summary>
        [Fact]
        public void RegistryTest()
        {
            // TODO unit test for the property 'Registry'
        }
    }
}
