/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing Plugin
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PluginTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Plugin
        //private Plugin instance;

        public PluginTests()
        {
            // TODO uncomment below to create an instance of Plugin
            //instance = new Plugin();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Plugin
        /// </summary>
        [Fact]
        public void PluginInstanceTest()
        {
            // TODO uncomment below to test "IsType" Plugin
            //Assert.IsType<Plugin>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'AuthorName'
        /// </summary>
        [Fact]
        public void AuthorNameTest()
        {
            // TODO unit test for the property 'AuthorName'
        }

        /// <summary>
        /// Test the property 'AuthorUrl'
        /// </summary>
        [Fact]
        public void AuthorUrlTest()
        {
            // TODO unit test for the property 'AuthorUrl'
        }

        /// <summary>
        /// Test the property 'PluginUrl'
        /// </summary>
        [Fact]
        public void PluginUrlTest()
        {
            // TODO unit test for the property 'PluginUrl'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'Thumb'
        /// </summary>
        [Fact]
        public void ThumbTest()
        {
            // TODO unit test for the property 'Thumb'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Upgrade'
        /// </summary>
        [Fact]
        public void UpgradeTest()
        {
            // TODO unit test for the property 'Upgrade'
        }

        /// <summary>
        /// Test the property 'Hooks'
        /// </summary>
        [Fact]
        public void HooksTest()
        {
            // TODO unit test for the property 'Hooks'
        }

        /// <summary>
        /// Test the property 'Tools'
        /// </summary>
        [Fact]
        public void ToolsTest()
        {
            // TODO unit test for the property 'Tools'
        }
    }
}
