/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseGetAllowedMimetypes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseGetAllowedMimetypesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseGetAllowedMimetypes
        //private ResponseGetAllowedMimetypes instance;

        public ResponseGetAllowedMimetypesTests()
        {
            // TODO uncomment below to create an instance of ResponseGetAllowedMimetypes
            //instance = new ResponseGetAllowedMimetypes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseGetAllowedMimetypes
        /// </summary>
        [Fact]
        public void ResponseGetAllowedMimetypesInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseGetAllowedMimetypes
            //Assert.IsType<ResponseGetAllowedMimetypes>(instance);
        }

        /// <summary>
        /// Test the property 'Allowed'
        /// </summary>
        [Fact]
        public void AllowedTest()
        {
            // TODO unit test for the property 'Allowed'
        }
    }
}
