/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing Status
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Status
        //private Status instance;

        public StatusTests()
        {
            // TODO uncomment below to create an instance of Status
            //instance = new Status();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Status
        /// </summary>
        [Fact]
        public void StatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" Status
            //Assert.IsType<Status>(instance);
        }

        /// <summary>
        /// Test the property 'VarStatus'
        /// </summary>
        [Fact]
        public void VarStatusTest()
        {
            // TODO unit test for the property 'VarStatus'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
