/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CheshireCatApi.Model;
using CheshireCatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CheshireCatApi.Test.Model
{
    /// <summary>
    ///  Class for testing WebResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebResponse
        //private WebResponse instance;

        public WebResponseTests()
        {
            // TODO uncomment below to create an instance of WebResponse
            //instance = new WebResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebResponse
        /// </summary>
        [Fact]
        public void WebResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebResponse
            //Assert.IsType<WebResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Fact]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }
    }
}
