/*
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CheshireCatApi.Client.OpenAPIDateConverter;

namespace CheshireCatApi.Model
{
    /// <summary>
    /// MemoryRecall
    /// </summary>
    [DataContract(Name = "MemoryRecall")]
    public partial class MemoryRecall : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MemoryRecall" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MemoryRecall() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MemoryRecall" /> class.
        /// </summary>
        /// <param name="query">query (required).</param>
        /// <param name="vectors">vectors (required).</param>
        public MemoryRecall(QueryData query = default(QueryData), VectorsData vectors = default(VectorsData))
        {
            // to ensure "query" is required (not null)
            if (query == null)
            {
                throw new ArgumentNullException("query is a required property for MemoryRecall and cannot be null");
            }
            this.Query = query;
            // to ensure "vectors" is required (not null)
            if (vectors == null)
            {
                throw new ArgumentNullException("vectors is a required property for MemoryRecall and cannot be null");
            }
            this.Vectors = vectors;
        }

        /// <summary>
        /// Gets or Sets Query
        /// </summary>
        [DataMember(Name = "query", IsRequired = true, EmitDefaultValue = true)]
        public QueryData Query { get; set; }

        /// <summary>
        /// Gets or Sets Vectors
        /// </summary>
        [DataMember(Name = "vectors", IsRequired = true, EmitDefaultValue = true)]
        public VectorsData Vectors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MemoryRecall {\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  Vectors: ").Append(Vectors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
